### ISSUE TITLE
Changing theme

### ISSUE THREAD

**Issue by mmguide2003** [codingfriend1/meanbase#3]
After changing the theme the site crashed:

    server/components/index/index.js:15
	root = app.get('appPath');
	          ^
     TypeError: Cannot read property 'get' of undefined
        at module.exports (..../mean2/server/components/index/index.js:15:12)
        at Immediate.<anonymous> (..../mean2/server/api/themes/themes.controller.js:28:5)
        at Immediate._onImmediate (....../mean2/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
        at processImmediate [as _immediateCallback] (timers.js:358:17)

Unfortunately I can no longer get the site running on local server now.

**Comment by codingfriend1** [comment]
Thank you for brining this to my attention. Sorry it takes so long, I'm working on this and a full time job. Tell me if the latest changes solve this for you.

**Comment by mmguide2003** [comment]
Thanks but on grunt serve:
    
    creating roles...
    module.js:338
    throw err;
    ^
    Error: Cannot find module 'fs-finder'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (....../server/components/search-folders/index.js:4:14)

**Comment by codingfriend1** [comment]
I've pushed a lot of fixed recently try pulling down the latest and running an npm install.
