### ISSUE TITLE
Error: Bower components directory does not exist at /Users/home/IdeaProjects/meanbase/public/admin/bower_components

### ISSUE THREAD

**Issue by RELATO** [codingfriend1/meanbase#9]
Please,
Macintosh:public home$ cd 
Macintosh:~ home$ node -v
v6.7.0
Macintosh:~ home$ npm -v
3.10.8
Macintosh:~ home$ bower -v
1.7.9
Macintosh:~ home$ gulp -v
[09:10:46] CLI version 1.2.2

How to solve this:

[09:00:00] Using gulpfile ~/IdeaProjects/meanbase/gulpfile.js
[09:00:00] Starting 'default'...
[09:00:00] Starting 'admin'...
[09:00:00] Starting 'copy-fonts-admin'...
[09:00:00] Finished 'copy-fonts-admin' after 53 ms
[09:00:00] Starting 'create-bower-admin'...
[09:00:00] 'create-bower-admin' errored after 2.12 ms
[09:00:00] Error: Bower components directory does not exist at /Users/home/IdeaProjects/meanbase/public/admin/bower_components
    at Error (native)
    at Object.module.exports (/Users/home/IdeaProjects/meanbase/node_modules/main-bower-files/lib/index.js:76:17)
    at Gulp.<anonymous> (/Users/home/IdeaProjects/meanbase/gulp/admin/bower.js:12:31)
    at module.exports (/Users/home/IdeaProjects/meanbase/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/home/IdeaProjects/meanbase/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/home/IdeaProjects/meanbase/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/home/IdeaProjects/meanbase/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/home/IdeaProjects/meanbase/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/home/IdeaProjects/meanbase/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)

**Comment by codingfriend1** [comment]
Did you run `npm run prepare` first?

**Comment by RELATO** [comment]
Yes,

"prepare": "npm install && npm run bower && gulp && webpack",

The above error was raised from gulp procedure.

**Comment by codingfriend1** [comment]
Hmmm, I tried cloning and starting from scratch but am not getting any errors. Here are my versions.

511 ~/Desktop/test/meanbase $ node -v
v5.8.0
512 ~/Desktop/test/meanbase $ npm -v
3.7.3
513 ~/Desktop/test/meanbase $ bower -v
1.7.9
514 ~/Desktop/test/meanbase $ gulp -v
[15:09:25] CLI version 3.9.1
[15:09:25] Local version 3.9.1

Perhaps it's the gulp version. Try `cd public/admin` and then `bower install`. I wonder if there is any error with folder permissions.

**Comment by RELATO** [comment]
Thanks,

I managed to get installed the same versions of yours. Not solved. 

Going to public/admin and then bower install I noticed that the installation folder of bower package was actually public/admin/public/lib instead of public/admin/bower_components. 

Then I tried to swap bower_component location on gulp/admin/bower.js to

bowerDirectory: folders.root + '/public/lib', instead of bowerDirectory: folders.root + '/bower_components',

And after that the gulp processed everything OK ( successfully )

Going deeper, now I have errors on webpack complaining about the bower_components like so:

 ERROR in ./~/css-loader!./~/stylus-loader!./public/app/app.styl
    Module not found: Error: Cannot resolve 'file' or 'directory' ./bower_components/bootstrap/fonts/glyphicons-halflings-regular.eot in /Users/home/IdeaProjects/meanbase/public/app
     @ ./~/css-loader!./~/stylus-loader!./public/app/app.styl 6:95-173 6:196-274
    
 ERROR in ./~/css-loader!./~/stylus-loader!./public/app/app.styl
    Module not found: Error: Cannot resolve 'file' or 'directory' ./bower_components/bootstrap/fonts/glyphicons-halflings-regular.eot in /Users/home/IdeaProjects/meanbase/public/app
     @ ./~/css-loader!./~/stylus-loader!./public/app/app.styl 6:95-173 6:196-274
    
  ERROR in ./~/css-loader!./~/stylus-loader!./public/admin/code/app.styl
    Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/mdl-pack/icons/MaterialIcons-Regular.eot in /Users/home/IdeaProjects/meanbase/public/admin/code
     @ ./~/css-loader!./~/stylus-loader!./public/admin/code/app.styl 6:133-204
    
Thanks in advance!

**Comment by codingfriend1** [comment]
If you took that route you would also have to update the bower paths of the fonts in `public/admin/code/app.styl` lines 26-39. I don't have anything in the code that tells bower_components to install in the public/lib folder. Do you think that could be a global setting you have for bower_components?
